{% set name = "wagtail-inventory" %}
{% set version = "3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 989b05928d1283db155d9d47732053829f568cffa7f5925087db96b88acca890

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=43.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - tqdm >=4.15.0,<5
    - wagtail >=6.2
    - django-autocomplete-light >=3.9

test:
  imports:
    - wagtailinventory
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Wagtail report to filter pages by block content
  home: https://github.com/cfpb/wagtail-inventory
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
