{% set name = "wagtail-inventory" %}
{% set version = "3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 203748a7eb15191852360682bf01400adeff12c74fb8079ff1c5452295dda524

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=43.0.0
    - wheel
    - pip
  run:
    - python >=3.8
    - tqdm >=4.15.0,<5
    - wagtail >=6.2
    - django-autocomplete-light >=3.9

test:
  imports:
    - wagtailinventory
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Wagtail report to filter pages by block content
  home: https://github.com/cfpb/wagtail-inventory
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
